version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    open-pull-requests-limit: 20
    reviewers:
      - ftonato
    assignees:
      - ftonato
    versioning-strategy: increase
