version: 2
jobs:
  build:
    docker:
      - image: cimg/node:18.19.0

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: build
          command: yarn build

      - run:
          name: test
          command: yarn test
